### ISSUE TITLE
TypeError: Cannot assign string to property USPS\USPSBase::$errorCode of type int

### ISSUE THREAD

**Issue by ProCycle** [GeNyaa/USPS-php-api#11]
TypeError: Cannot assign string to property USPS\USPSBase::$errorCode of type int in USPS\USPSBase->setErrorCode() (line 368 of genyaa/usps-php-api/src/USPSBase.php)

genyaa/usps-php-api/src/USPSBase.php(219): USPS\USPSBase->setErrorCode()
genyaa/usps-php-api/src/Rate.php(27): USPS\USPSBase->doRequest()

I cannot reproduce it on my end, having the customer try again while USPS API response logging is enabled in the hopes that I catch what is wrong with the response.

**Comment by ProCycle** [comment]
Unfortunately after enabling logging the problem ceased so the customer was unable to reproduce it again. I'm guessing it's problem with USPS API returning the wrong thing in the response. I will keep an eye out for more instances of the error

**Comment by GeNyaa** [comment]
From what I can tell it's trying to assign a string to an integer-only allowed variable. I think I know where the issue lies.
As soon as I have a little bit of time I'll roll out a patch. From what I can tell it's not very common.

**Comment by GeNyaa** [comment]
Rolled out a fix for this. This should not be happing anymore. Upgrade to 2.0.3
