### ISSUE TITLE
TypeError: Cannot assign bool to property USPS\USPSBase::$response of type string in USPS\USPSBase->setResponse()

### ISSUE THREAD

**Issue by SAH62** [GeNyaa/USPS-php-api#9]
I just ran into the subject error when trying to save a Drupal Commerce shipment. Here's the code that's involved:

```
    /**
     * Set the response.
     */
    public function setResponse(mixed $response = ''): self
    {
        $this->response = $response;
        return $this;
    }
```
The issue is that the value of $response can be a boolean value *or* a string value. It can be boolean FALSE if, for example, the call to curl_exec from this line in function doRequest() fails:

```
$this->setResponse(curl_exec($ch));
```

If curl_exec fails, it's returns boolean FALSE and the attempt to assign FALSE to $this->response produces the TypeError. Here's a suggested fix:

```
    /**
     * Set the response.
     */
    public function setResponse(mixed $response = ''): self
    {
        if (is_string($response)) {
            $this->response = $response;
        }
        else {
            $this->response = '';
        }

        return $this;
    }
```

**Comment by GeNyaa** [comment]
Rolled out a fix for this @SAH62 v2.0.2 should no longer have this issue.
